# Generated by Django 5.2.4 on 2025-08-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs7_FBV_Browser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='std',
        ),
    ]
